---

-
  name: "Clean Ubuntu Resin Instance - Show Ansible Role variables"
  debug: 
    msg: 
      - "curi_log_files_remove_enabled={{curi_log_files_remove_enabled|default('<UNDEFINED>')}}"
      - "curi_log_files_targets={{curi_log_files_targets|default('<UNDEFINED>')}}"
      - "curi_temp_files_remove_enabled={{curi_temp_files_remove_enabled|default('<UNDEFINED>')}}"
      - "curi_temp_files_targets={{curi_temp_files_targets|default('<UNDEFINED>')}}"



#clean-log-files

- 
  name: "Clean Ubuntu Resin Instance - Find log files"
  find:
    paths: "{{ item['curi_log_files_paths'] }}"
    patterns: "{{ item['curi_log_files_patterns'] }}"
    age: "{{ item['curi_log_files_age'] | default('180d') }}" # para los logs se tiene en cuenta la antiguedad del archivo
    recurse: "{{ item['curi_log_files_recurse'] | default(true) }}"
    hidden: "{{ item['curi_log_files_hidden'] | default(true) }}"
    file_type: "{{ item['curi_log_files_file_type'] | default('file') }}" # para los logs solo borramos los archivos, no los directorios
    follow: "{{ item['curi_log_files_follow'] | default(false) }}"
  register: curi_log_files_find_results
  with_items: "{{curi_log_files_targets}}"
  when: 
    - curi_log_files_find_enabled is undefined or (curi_log_files_find_enabled is defined and curi_log_files_find_enabled == true) # enabled by default
    - curi_log_files_targets is defined

-
  name: "Clean Ubuntu Resin Instance - Show finded files"
  debug: 
    msg: 
      - "{{ (item.files | map(attribute='path') | list) }}"
  with_items: "{{curi_log_files_find_results.results|flatten}}"
  when: 
    - curi_log_files_find_results is defined

- # magia
  name: "Clean Ubuntu Resin Instance - Prepare log files list" # transforma el list de files encontrados a un list de strings que son los paths solamente 
  set_fact:  
    curi_log_files_find_results_prepared: "{{ (curi_log_files_find_results_prepared | default([])) + (item.files | map(attribute='path') | list) }}" # toma la array de objetos "files", se queda solo con el atributo "path" de cada objeto y lo convierte a "list" para que pueda ser mostrada en un debug msg
    # NOTA: combinar el set_fact con el with_items hace que se concatenen los items del with_items dntro de la variable del set_fact
    # NOTA2: el default([]) es para instanciar una list vacia en la 1ra iteracion ya que "curi_log_files_find_results_prepared"  no existira en la 1ra.
  with_items: "{{curi_log_files_find_results.results|flatten}}" # aplana el array de arrays
  when: 
    - curi_log_files_find_results is defined

-
  name: "Clean Ubuntu Resin Instance - Show prepared log files list"
  debug: 
    msg: "{{ curi_log_files_find_results_prepared  }}" 
  when:
    - curi_log_files_show_enabled is undefined or (curi_log_files_show_enabled is defined and curi_log_files_show_enabled == true) # enabled by default
    - curi_log_files_find_results_prepared is defined

- 
  name: "Clean Ubuntu Resin Instance - Remove log files"
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ curi_log_files_find_results_prepared }}"
  when:
    - curi_log_files_remove_enabled is undefined or (curi_log_files_remove_enabled is defined and curi_log_files_remove_enabled == true) # enabled by default
    - curi_log_files_find_results_prepared is defined



#clean-temp-files

- 
  name: "Clean Ubuntu Resin Instance - Find temp files"
  find:
    paths: "{{ item['curi_temp_files_paths'] }}"
    patterns: "{{ item['curi_temp_files_patterns'] }}"
    recurse: "{{ item['curi_temp_files_recurse'] | default(true) }}"
    hidden: "{{ item['curi_temp_files_hidden'] | default(true) }}"
    file_type: "{{ item['curi_temp_files_file_type'] | default('any') }}"
    follow: "{{ item['curi_temp_files_follow'] | default(false) }}"
  register: curi_temp_files_find_results
  with_items: "{{curi_temp_files_targets}}"
  when: 
    - curi_temp_files_find_enabled is undefined or (curi_temp_files_find_enabled is defined and curi_temp_files_find_enabled == true) # enabled by default
    - curi_temp_files_targets is defined

-
  name: "Clean Ubuntu Resin Instance - Show finded files"
  debug: 
    msg: 
      - "{{ (item.files | map(attribute='path') | list) }}"
  with_items: "{{curi_temp_files_find_results.results|flatten}}"
  when: 
    - curi_temp_files_find_results is defined

- # magia
  name: "Clean Ubuntu Resin Instance - Prepare temp files list" # transforma el list de files encontrados a un list de strings que son los paths solamente 
  set_fact:  
    curi_temp_files_find_results_prepared: "{{ (curi_temp_files_find_results_prepared | default([])) + (item.files | map(attribute='path') | list) }}" # toma la array de objetos "files", se queda solo con el atributo "path" de cada objeto y lo convierte a "list" para que pueda ser mostrada en un debug msg
    # NOTA: combinar el set_fact con el with_items hace que se concatenen los items del with_items dntro de la variable del set_fact
    # NOTA2: el default([]) es para instanciar una list vacia en la 1ra iteracion ya que "curi_temp_files_find_results_prepared"  no existira en la 1ra.
  with_items: "{{curi_temp_files_find_results.results|flatten}}" # aplana el array de arrays
  when: 
    - curi_temp_files_find_results is defined

-
  name: "Clean Ubuntu Resin Instance - Show prepared temp files list"
  debug: 
    msg: "{{ curi_temp_files_find_results_prepared  }}" 
  when:
    - curi_temp_files_show_enabled is undefined or (curi_temp_files_show_enabled is defined and curi_temp_files_show_enabled == true) # enabled by default
    - curi_temp_files_find_results_prepared is defined

- 
  name: "Clean Ubuntu Resin Instance - Remove temp files"
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ curi_temp_files_find_results_prepared }}"
  when:
    - curi_temp_files_remove_enabled is undefined or (curi_temp_files_remove_enabled is defined and curi_temp_files_remove_enabled == true) # enabled by default
    - curi_temp_files_find_results_prepared is defined
